<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$item = $block->getSaleableItem();

?>
<?php if ($block->hasSpecialPrice()):?>
    <span class="special-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <?php if ($item->getData('mrp_price')): ?>
        <?php $mrp = number_format($item->getData('mrp_price'), 2); ?>
        <span class="old-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-label">Regular Price</span>
        <span id="old-price" data-price-amount="<?= $mrp ?>" data-price-type="oldPrice" class="price-wrapper "><span class="price">₹<?= $mrp; ?></span></span>
        </span>
        </span>
    <?php else: ?>
        <span class="old-price">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
        </span>
    <?php endif; ?>
<?php else:?>
   <span class="special-price">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
   </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()):?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
<?php if ($schema): ?>
<span class="price-tax-note">Exclusive of GST <?php echo $item->getGst()."%"; ?></span>
<?php endif; ?>